before_script:
  - docker info

build_image_develop:
  stage: build
  script:
    - docker build frontend -t docker.maxiv.lu.se/ops-fixlist-frontend-test
    - docker build backend -t docker.maxiv.lu.se/ops-fixlist-backend-test
    - docker push docker.maxiv.lu.se/ops-fixlist-frontend-test
    - docker push docker.maxiv.lu.se/ops-fixlist-backend-test
  only:
    - develop

build_image:
  stage: build
  script:
    - docker build frontend -t docker.maxiv.lu.se/ops-fixlist-frontend
    - docker build backend -t docker.maxiv.lu.se/ops-fixlist-backend
    - docker push docker.maxiv.lu.se/ops-fixlist-frontend
    - docker push docker.maxiv.lu.se/ops-fixlist-backend
  only:
    - master
